# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "building"
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -y --no-install-recommends texlive-full
      - run: xelatex -interaction=nonstopmode -halt-on-error *.tex
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "testing"
  deploy:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "deploying"

workflows:
  build_and_test:
    jobs:
      - build